### ISSUE TITLE
Clarification regarding blocklists

### ISSUE THREAD

**Issue by spekulatius** [climate-strike/license#12]
Hello,

I've checked the blocklist and wasn't entirely sure, if the [second list](https://github.com/climate-strike/license/tree/master/blocklist#companies-listed-as-either-oil--gas-drilling-oil--gas-equipment--services-oil--gas-midstream-oil--gas-ep-oil--gas-refining--marketing-or-oil--gas-integrated-on-the-nasdaq-or-nyse-exchanges) is excluded from using the software as well. Maybe something worth to expand on / clarify further?

Cheers,
Peter

**Comment by frnsys** [comment]
Thanks for your interest in the project and for bringing this up. We were in the process of figuring out the best way to develop a blocklist so those two lists resulted from two different approaches...we'll harmonize them soon or figure out a better approach. The approach mentioned in #8 suggesting use of SIC sounds like a good way to go about it, for example. I'll open a separate issue regarding the harmonization of these lists.
